### ISSUE TITLE
Remove racist political statements supporting communism from your website

### ISSUE THREAD

**Issue by somewhatlogical** [PowerShell/PowerShellGallery#111]
I see your "moderator" closed the other two open issues regarding this matter.

If your claim is that "Black Lives Matter" does not mean only black lives matter, then why does your website not state "All Lives Matter," which is the purported claim by your moderator.  I mean you don't throw ANYTHING on your website for any other issue on earth (hey man, like someone everyone can get behind -- like... cancer, aids, general racism, etc.) -- except this racist and Marxist organization attempting to sow dissent.  You aren't even supporting black lives, you are supporting the organization, hence your proper pronoun usage and capitalization.  So, it's not even black lives that matter, its the organization Black Lives Matter that you are in support of.  So you're not only wrong, but stupid.  In fact, I'm also questioning in what way the political affiliations of a small percentage of people is now the prominent issue of focus on PowerShell Gallery -- and not PowerShell!

This issue should be escalated accordingly rather than twisting your CEO's words.  If your CEO is aware of your actions, then why is "Black Lives Matter" not prominently displayed on any other Microsoft webpage?  Why are the issues being closed to attempt to hide them without discussion.  This is not your official company stance (trust me, I know).  This support of a racist, Marxist/communist/socialist political organization is disallowed.  Remove the statement, or the issue may be escalated internally beyond the psychos seemingly in control of something that supposedly is to do with "PowerShell."  I doubt the people this will be escalated to would be pleased to see the rogue actions of PowerShell Gallery.

**Comment by TylerLeonhardt** [comment]
Thanks for you feedback, if you read the link I posted in:
https://github.com/PowerShell/PowerShellGallery/issues/109#issuecomment-658561907

It tells you why saying "Black Lives Matter" is important.

"All Lives Matter" is a true statement, however, it is being said in response to the folks saying "Black Lives Matter".

Here's a snippet from the link:

"saying “all lives matter” as a rebuttal to Black Lives Matter is an attempt to suppress the focus on black lives. It’s inherently disingenuous, because it can’t be true that all lives matter until black lives matter, too."

Here's a comic to help illustrate:
![BLM](http://chainsawsuit.com/wp-content/uploads/2016/07/20160707_allhousesredux.png)

If you want, you can tweet at Satya if you want to complain to our CEO (there might be other ways, I'm not sure) but there's no word twisting here, only support and love for the black community.

**Comment by jack-work** [comment]
I'm curious why you think that Microsoft, one of the world's largest corporations, would have any interest in supporting communism or Marxism, a philosophy that suggests that power and money should be stripped from large corporations and redistributed.
