### ISSUE TITLE
Dead FAQ link

### ISSUE THREAD

**Issue by exchange12rocks** [PowerShell/PowerShellGallery#150]
On the https://www.powershellgallery.com/policies/Contact page there's a link https://docs.microsoft.com/en-us/powershell/gallery/faqs - that link does not work anymore.

**Comment by SydneyhSmith** [comment]
@exchange12rocks thanks for catching that!

**Comment by R3ality** [comment]
Confirming that this issue is still valid as the link referenced in https://github.com/PowerShell/PowerShellGallery/issues/150#issue-778179320 above appears to be unchanged

Furthermore, the "FAQs" link in the footer of any and all PSGallery pages also results in the same "404 - Page not found". 
![image](https://user-images.githubusercontent.com/762122/166455230-98f2c644-a2bb-4e72-a7d3-c627c498a3de.png)

Although that link is defined differently as https://aka.ms/PSGalleryPreviewFAQ it still redirects to the same https://docs.microsoft.com/en-us/powershell/gallery/faqs. Thus I have not opened a separate issue for it on GitHub.

The correct link for both cases would probably be https://docs.microsoft.com/en-us/powershell/scripting/gallery/faqs although I have no direct affiliation with Microsoft to confirm this.

**Comment by SydneyhSmith** [comment]
Just fixed this let me know if you are still hitting it
