### ISSUE TITLE
Account: Change of E-Mail Address https://www.powershellgallery.com

### ISSUE THREAD

**Issue by carsten-riedel** [PowerShell/PowerShellGallery#233]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [x] Search the existing issues.

### Steps to reproduce

Seems to be a duplicate, but it don't get fixed so i address this topic solely again

Case 1)
1) Login to powershell https://www.powershellgallery.com
2) Go to account settings
3) Change E-Mail
4) Enter the new E-Mail

Case 2)
1) Login to powershell https://www.powershellgallery.com
2) Go to Contact Us
3) Fill out Subject Line and Message for support
4) Check Send me a copy

### Expected behavior

```console
Case 1)
Receiving a E-Mail in case 1 at my new account

Case 2)
Receiving a E-Mail in case 2 at my current account
```

### Actual behavior

```console
I don't receive any E-Mail (resend serveral times, waited around 24 hours)
```

### Error details

```console
none
```

### Environment data

```PowerShell
https://www.powershellgallery.com
https://www.powershellgallery.com/policies/Contact
```

### Version

Website

**Comment by Sylfwood** [comment]
Same problem here! Still waiting for support.

Probably related to this [issue](https://github.com/PowerShell/PowerShellGallery/issues/221).

**Comment by anamnavi** [comment]
Hi @carsten-riedel and @Sylfwood, our apologies for the inconvenience. Unfortunately this is due to an email relay issue we're working to resolve. In the meantime, if you could email us at PSGallerySupport@microsoft.com with the issue you're facing and need an email change for we'd be happy to resolve it. Thanks!

**Comment by Sylfwood** [comment]
Hi @anamnavi, I tried to reach you at PSGallerySupport@microsoft.com in September, but I didn't get any response from you. Is this normal?

**Comment by Sylfwood** [comment]
I also tried to email you at psgallery@microsoft.com as suggest in this [thread](https://github.com/PowerShell/PowerShellGallery/issues/234#issuecomment-1262654575). But I received a message back from postmaster@microsoft.com mentioning this error :
`Your message wasn't delivered because the recipient's email provider rejected it.`

**Comment by anamnavi** [comment]
@Sylfwood sorry for this happening, I think I unfortunately missed it. Can you email it again to psgallerysupport@microsoft.com, and I'll be on the lookout so I can resolve it this week.

**Comment by Sylfwood** [comment]
> @Sylfwood sorry for this happening, I think I unfortunately missed it. Can you email it again to [psgallerysupport@microsoft.com](mailto:psgallerysupport@microsoft.com), and I'll be on the lookout so I can resolve it this week.

I have sent you a new email

**Comment by anamnavi** [comment]
Closing this as it was resolved via email. Feel free to reach out if there are any other issues, thanks!
