### ISSUE TITLE
Searching for Az Package in PowershellGallery does not return the package in results

### ISSUE THREAD

**Issue by bganapa** [PowerShell/PowerShellGallery#25]
search this Az
https://www.powershellgallery.com/packages?q=AZ

The following package is not  in the result. This is supposed to be the new Azure powershell uber module
https://www.powershellgallery.com/packages/Az/0.1.0

**Comment by JKeithB** [comment]
The item is there, but it's not in the first view.
One thing to be aware of is that searching for AZ, with no field specified for search critieria, searches all information we have about the item and not just search the title.
If you specify title:az, then this shows up in the first page, but not where I expected (which is why I'm leaving this open.) Items with "AZ." get listed before "AZ" (without the "."). I would have expected AZ by itself to be the top of the list, but it's in the middle of the set. 

The initial default sort is by relevance, & AZ shows up about 4 pages in. 
If you sort alphabetically, AZ shows up on the 2nd page. That's because the search includes all items that have AZ in them will be brought up, then sorts those by title alphabetically. 
If you sort by "recent', it ends up at the top.

**Comment by edyoung** [comment]
It seems like an exact match on the module name should rank higher than a match somewhere in the description. Right now the search is not smart enough to do that.

**Comment by SydneyhSmith** [comment]
Closing as resolved
