### ISSUE TITLE
PSGallery search is broken

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/PowerShellGallery#282]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

Go to poweshellgallery.com and search for a package. No results are returned intermittently.

### Expected behavior

```console
Results are returned.
```

### Actual behavior

```console
No results are returned.
```

### Environment data

```PowerShell
N/A
```

### Version

N/A

**Comment by alerickson** [comment]
What terms are you searching? I haven't been able to repro this yet, but I'll testing since the issue is intermittent.  Also checking if there's anything unusual in our logs

**Comment by ThomasNieto** [comment]
PSReadline

**Comment by alerickson** [comment]
I haven't been able to find anything unusual yet. Someone on the team mentioned a similar issue around the same time, but hasn't been able to repro it since then.  Is this issue still intermittently persisting? If it is, can you comment with what you search term you were using the time you made the query?

**Comment by ThomasNieto** [comment]
I can't reproduce it anymore. It must have been a short term issue.
